Restored commands to run "make migrate" in YAML files that were erroneously removed.

diff --git a/.github/workflows/restore_rds.yml b/.github/workflows/restore_rds.yml
--- a/.github/workflows/restore_rds.yml
+++ b/.github/workflows/restore_rds.yml
@@ -169,7 +169,7 @@ jobs:
           echo "DATABASE_URL exported."
 
           echo "Running database migrations (make migrate)..."
-
+          make migrate settings="app.settings.${ENVIRONMENT}" || { echo "ERROR: 'make migrate' failed"; exit 1; }
           echo "'make migrate' completed."
 
           echo "Migration step finished successfully."
